# Introduction to Python, iPython and Jupyter notebooks

## Python essentials for R users

### Comparisons with R

Differences with R
- Python was invented in the 80s by Guido van Rossum
- It's a general purpose programming language which we can do scientific computing in (rather than a scientific computing language which we can do programming in, like R)
- Tabs matter, not curly braces
- Assignment is with `=`, not `<-`


Similarities to R
- Good IDEs are free (e.g. pycharm)
- As in R, everything is an object, and functions are first-class objects
- Standard equations in the interpreter
- numpy arrays in python are roughly the equivalent vectors/matrices in R
- pandas Data.Frames are the equivalent of R data.frames

### The SciPy Ecosytem

![image](../images/scipy_stack.png)

## iPython and Jupyter essentials for R users

### equations

We can run basic mathematical operations in a code cell and store them in variables, just like in r

In [1]:
# e.g.
x = (7 ** 2) / 3

### magics

ipython "magics" let us do cool things in cells. They are accessed used the `%` symbol. 

There's a even magic to list common magics: `%quickref`

Two of the most commonly used are timing in the notebook, or checking history in ipython.

In [2]:
import numpy as np

In [3]:
# runs it ones and times it
%time lambda x: np.sort(np.random.normal(1000))

CPU times: user 27 µs, sys: 0 ns, total: 27 µs
Wall time: 4.29 µs


<function __main__.<lambda>(x)>

In [4]:
# runs many (depending on runtime) loops and gives us summary statistics
%timeit lambda x: np.sort(np.random.normal(1000))

38.7 ns ± 1.39 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [5]:
# gives us everything we have run
%hist

# e.g.
x = (7 ** 2) / 3
import numpy as np
# runs it ones and times it
%time lambda x: np.sort(np.random.normal(1000))
# runs many (depending on runtime) loops and gives us summary statistics
%timeit lambda x: np.sort(np.random.normal(1000))
# gives us everything we have run
%hist


We can also save it to a file as below (again, useful for ipython rather than jupyter)

```%history -g -f filename```

### accessing bash

We can run basic bash commands directly from notebook cells

In [6]:
pwd

'/Users/seafloor/scientific_pythonn_tutorial/notebooks'

In [7]:
ls

01 - Introduction.ipynb


And we can run more complicated lines by adding a `!` to the start

In [10]:
# will error-out
# wc -l ../README.txt

In [27]:
!wc -l ../README.md

      54 ../README.md


### help

We can look-up help using the `?` notation

In [12]:
?%time

Docstring:
Time execution of a Python statement or expression.

The CPU and wall clock times are printed, and the value of the
expression (if any) is returned.  Note that under Win32, system time
is always reported as 0, since it can not be measured.

This function can be used both as a line and cell magic:

- In line mode you can time a single-line statement (though multiple
  ones can be chained with using semicolons).

- In cell mode, you can time the cell body (a directly
  following statement raises an error).

This function provides very basic timing functionality.  Use the timeit
magic for more control over the measurement.

.. versionchanged:: 7.3
    User variables are no longer expanded,
    the magic line is always left unmodified.

Examples
--------
::

  In [1]: %time 2**128
  CPU times: user 0.00 s, sys: 0.00 s, total: 0.00 s
  Wall time: 0.00
  Out[1]: 340282366920938463463374607431768211456L

  In [2]: n = 1000000

  In [3]: %time sum(range(n))
  CPU times: user 1.20 s,

In [13]:
?np.load

Signature:
np.load(
    file,
    mmap_mode=None,
    allow_pickle=False,
    fix_imports=True,
    encoding='ASCII',
)
Docstring:
Load arrays or pickled objects from ``.npy``, ``.npz`` or pickled files.

.. warning:: Loading files that contain object arrays uses the ``pickle``
             module, which is not secure against erroneous or maliciously
             constructed data. Consider passing ``allow_pickle=False`` to
             load data that is known not to contain object arrays for the
             safer handling of untrusted sources.

Parameters
----------
file : file-like object, string, or pathlib.Path
    The file to read. File-like objects must support the
    ``seek()`` and ``read()`` methods and must always
    be opened in binary mode.  Pickled files require that the
    file-like object support the ``readline()`` method as well.
mmap_mode : {None, 'r+', 'r', 'w+', 'c'}, optional
    If not None, then memory-map the file, using the given mode (see
    `numpy.memmap` f

While `?` gives the docstring, `??` gives the full code for the function.

We can also use tab-completion to get the arguments and docstring for a function on-the-fly

### Importing and style

We can run any of the following to import a function or module from a library (package)
- `import pandas` (gives us access to everything through pandas.function
- `import pandas as pd` (the canonical and recommended way to import)
    + other common ones are `import numpy as np`, `import seaborn as sns`, `import matplotlib.pyplot as plt` etc.
- `from pandas import read_csv` (perfectly acceptable way if you only want one function)
- `from pandas import *` (never do this - brings every function into the namespace)

There's a well-known import everyone should run if they're going to be making python scripts:

In [14]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


### inspecting objects

In [15]:
type(x)

float

In [16]:
dir(x)

['__abs__',
 '__add__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getformat__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__le__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__setformat__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 'as_integer_ratio',
 'conjugate',
 'fromhex',
 'hex',
 'imag',
 'is_integer',
 'real']

## Getting data in/out

### making and runnning operations on numpy arrays

We create numpy arrays from lists and the `np.array()` function

In [17]:
# a 1-d array
np.array([0, 1, 2])

array([0, 1, 2])

Numpy arrays are like R matrices in that they are a single data type and can be n-dimensional arrays

In [18]:
# a 2-d array
np.array([[0, 1, 2], [3, 4, 5]])

array([[0, 1, 2],
       [3, 4, 5]])

We can access attributes of these arrays, like so:

In [19]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a.shape

(2, 3)

In [20]:
a.ndim

2

We can access methods on these arrays too:

In [21]:
a.sum()

15

In [22]:
a.mean(axis=0)

array([1.5, 2.5, 3.5])

And we can apply other functions from the numpy library to arrays, e.g.

In [23]:
# dot product of 2x3 and 3x4 matrices = 2x4 matrix
np.dot(np.array([[0, 1, 2], [3, 4, 5]]), np.array([[0, 1, 2, 4], [5, 6, 7, 8], [9, 10, 11, 12]]))

array([[ 23,  26,  29,  32],
       [ 65,  77,  89, 104]])

### making pandas DataFrames

In [28]:
import pandas as pd

In [29]:
# the named way
df = pd.DataFrame({'this': [0, 1, 2, 3],
                   'that': [4, 5, 6, 7]})
df.head()

this  that
0     0     4
1     1     5
2     2     6
3     3     7

In [30]:
# from a numpy array
df = pd.DataFrame(np.random.normal(size=(4, 2)),
                  columns=['this', 'that'])
df.head()

this      that
0 -1.114514 -0.185559
1  0.715849  0.785909
2 -0.279235  0.969821
3  0.197501  0.367976

### reading files

In [43]:
import io

In [44]:
# reading in a vcf
def read_vcf(path):
    with open(path, 'r') as f:
        lines = [l for l in f if not l.startswith('##')]
    df = (pd.read_csv(io.StringIO(''.join(lines)),
                      dtype={'#CHROM': int, 'POS': int, 'ID': str, 'REF': str, 'ALT': str,
                             'QUAL': str, 'FILTER': str, 'INFO': str},
                      sep='\t'))
    
    return df

In [45]:
df = read_vcf('../data/example.vcf')
df.head()

#CHROM       POS             ID REF ALT QUAL FILTER INFO
0      22  16287538  Affx-52233492   C   G    .      .    .
1      22  16287557    rs200923174   G   C    .      .    .
2      22  16287585  Affx-80289661   A  AC    .      .    .
3      22  16287663  Affx-80289662   T  TC    .      .    .
4      22  16287779  Affx-52336937   C  CT    .      .    .

In [32]:
# reading in a bim file
def read_bim(f):
    df = pd.read_csv(f, sep='\s+')
    df.columns = ['#CHROM', 'ID', 'CM', 'POS', 'ALT', 'REF']

    return df

In [46]:
df = read_bim('../data/example.bim')
df.head()

#CHROM             ID  CM       POS ALT REF
0      22  Affx-52233492   0  16287538   G   C
1      22    rs200923174   0  16287557   C   G
2      22  Affx-80289661   0  16287585  AC   A
3      22  Affx-80289662   0  16287663  TC   T
4      22  Affx-52336937   0  16287779  CT   C

In [33]:
# reading in a fam file
def read_fam(f):
    df = pd.read_csv(f, sep='\s+')
    df.columns = ['FID', 'IID', 'PAT', 'MAT', 'SEX', 'PHENO']
    
    return df

In [47]:
df = read_fam('../data/example.fam')
df.head()

FID   IID  PAT  MAT  SEX  PHENO
0  2345  2345    0    0    1      1
1  3456  3456    0    0    1      2
2  4567  4567    0    0    2      1
3  5678  5678    0    0    1      1
4  6789  6789    0    0    2      1

Common arguments to add:
  - `sep='\t'` or `sep='\s+'` (needed for sumstats or some plink outputs)
  - `compression='gzip'`
  - `header=None`
  - `usecols=['rs111', 'rs222']`
  - `na_values=99`

### extra: reading multiple files

In [34]:
# reading in multiple files
from glob import glob
files = sorted(glob('../data/*.csv'))
# df = pd.concat([pd.read_csv(f) for f in files])

reading multple files like this uses a list comprehension (a for loop that's written as a one-liner and which saves the output as a list). 

Format is:
- l = [f for f in files] # just lists all files
- l = [pd.read_csv(f) for f in files] # reads all files
- l = [f for f in files if 'chromosome_x' not in f] # reads only autosomes by adding an if statement
- l = [f if 'chromosome_x' not in f else print(f'skipping {f}') for f in files] # same but with logging using else statement

### writing files

In [35]:
# writing a SNP list for plink in/exclusions
# df['ID'].to_csv(f, header=None, index=False)

In [36]:
# writing ID list for plink in/exclusions
# df.loc[:, ['FID', 'IID']].to_csv(f, index=False, sep='\t', header=None)

In [37]:
# writing a VCF
def write_vcf(data, vcf_file, chrom='#CHROM', pos='POS', ids='ID', ref='REF', alt='ALT'):
    with open(vcf_file, 'w') as f:
        f.write('##fileformat=VCFv4.2\n'
                '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n')

    (data.loc[:, [chrom, pos, ids, ref, alt]]
         .assign(QUAL='.', FILTER='.', INFO='.')
         .to_csv(vcf_file, sep='\t', index=False, header=None, mode='a'))

In [38]:
def write_bim(data, f, chrom='#CHROM', pos='POS', ids='ID', ref='REF', alt='ALT'):
    (df.assign(CM=0)
       .loc[:, [chrom, ids, 'CM', pos, alt, ref]]
       .to_csv(f, sep='\t', index=False, header=None))

# Basics of working with dataframes

To cover:
- accessing columns and index
- converting to numpy
- square bracket notation but with .loc and .iloc
- adding new columns
- sorting